# -*- coding: utf-8 -*-
"""atividade 20/05

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1evqXjHz1QwX-VzUPVpTGrl_Kj5aGRv6F

**Atividade:**

1. O usuário deve iniciar com um saldo inicial de R$1000,00.
2. O sistema deve permitir as seguintes operações:
Consultar saldo
Sacar dinheiro (com verificação de saldo suficiente)
3. O programa deve utilizar uma estrutura de repetição while para manter o sistema
em execução contínua.
4. O usuário deve ter a opção de encerrar o programa quando desejar.
5. O sistema deve apresentar um menu de opções para interação com o usuário.
6. O programa deve tratar entradas inválidas de forma adequada (por exemplo, opções
inexistentes ou valores negativos).
"""

saldo = 1000
hist = []

while True:
    print(f"\nSaldo: R$ {saldo}")
    op = input(" 1-Saque | 2-Histórico | 3-Sair: ")

    if op == '3': break

    elif op == '1':
        v = float(input("Valor: "))
        if 0 < v <= saldo and v <= 500: # Tudo em uma linha só!
            saldo -= v
            hist.append(f"- R$ {v}")
        else:
            print("Saque negado (Saldo insuficiente ou limite R$500 excedido)")

    elif op == '2':
        print(f"Extrato: {hist}")