# -*- coding: utf-8 -*-
"""atividade 20/05

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1evqXjHz1QwX-VzUPVpTGrl_Kj5aGRv6F
"""

saldo = 1000
hist = []

while True:
    print(f"\nSaldo: R$ {saldo}")
    op = input(" 1-Saque | 2-Histórico | 3-Sair: ")

    if op == '3': break

    elif op == '1':
        v = float(input("Valor: "))
        if 0 < v <= saldo and v <= 500: # Tudo em uma linha só!
            saldo -= v
            hist.append(f"- R$ {v}")
        else:
            print("Saque negado (Saldo insuficiente ou limite R$500 excedido)")

    elif op == '2':
        print(f"Extrato: {hist}")